### ISSUE TITLE
main.pdf

### ISSUE THREAD

**Issue by Saku25** [javo92/Redaccion-TFM-LaTeX#1]
Mejoras en un primer vistazo:

Tabla 3.1. Referencia de dónde la has sacado
Fig. 3.6. Lo mismo

Página 16. .....y PDFs... Queda mal. Pon algo como documentación, no PDFs.
Página 18. Dropout y datasheet inglés. Todo el inglés en cursiva.
Página 19. Tras los ":" no va mayúscula. El tercer párrafo hay que reestructurarlo. Luego cuando me lo 
                 releea te doy ideas.
Apartado 3.3.2. Muchos "así como". Cambia  la expresión. En la figura 3.11 o 14 lo mismo.
Página 22.  Cuando haces referencias de [] deja un espacio entre la palabra y la referencia

**Comment by javo92** [comment]
Todos los puntos arreglados salvo por el de la página 19 que habrá que verlo con más calma.
